### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by likapantrip** [likapantrip/furima-41468#24]
# メッセージ
本番環境の挙動確認をお願いします。

# URL
https://furima-41468.onrender.com

**Comment by motomuun** [comment]
ご提出ありがとうございます‼︎
動作の確認をしたところ、1点だけ修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品出品機能の確認**

- [x] **手数料と利益の合計が販売価格と一致しません。一致するように修正をお願いします。**
<img width="701" alt="スクリーンショット 2024-10-24 16 09 10" src="https://github.com/user-attachments/assets/b6860e73-9829-4f1f-904d-c55c99261c42">



修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by likapantrip** [comment]
# メッセージ
指摘内容を修正しました。再度確認お願いします。

# 修正内容
## 修正履歴
https://github.com/likapantrip/furima-41468/pull/25#issue-2610759618

## 本番環境での動作確認
[![Image from Gyazo](https://i.gyazo.com/d9a550d2b6ed02e1cd2214b23bdbb816.png)](https://gyazo.com/d9a550d2b6ed02e1cd2214b23bdbb816)

**Comment by koyamatakumi** [comment]
最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)

**Comment by likapantrip** [comment]
本番環境でのLGTMを受領したのでクローズ。
